version: '3.8'
services:
  modbus-server:
    build:
      context: .
      dockerfile: Dockerfile.modbus-server
    container_name: modbus-server
    ports:
      - "5020:5020"  # Expose Modbus TCP port
    networks:
      - modbus-net
    environment:
      - MODBUS_HOST=modbus-server
      - MODBUS_PORT=5020
    volumes:
      - ./modbus_server.py:/app/modbus_server.py
    restart: always

  node-red:
    build:
      context: .
      dockerfile: Dockerfile.node-red
    container_name: node-red
    ports:
      - "1880:1880"  # Expose Node-RED web UI
    networks:
      - modbus-net
    depends_on:
      - modbus-server
    volumes:
      - ~/.node-red:/data
    restart: always

networks:
  modbus-net:
    driver: bridge
