version: '3'
services:
  modbus:
    image: cybcon/modbus-server # Replace with your Modbus image if necessary
    container_name: modbus-server
    network_mode: "host"  # Use host networking mode for the Modbus server
    ports:
      - "5020:5020"  # Modbus TCP port
    # no need for networks section when using host networking
  
  node-red:
    image: nodered/node-red
    container_name: node-red
    network_mode: "host"  # Use host networking mode for Node-RED
    ports:
      - "1880:1880"  # Node-RED web interface port
    environment:
      - NODE_RED_USERNAME=your-username
      - NODE_RED_PASSWORD=your-password
    volumes:
      - ./node-red:/data  # Persist Node-RED data
    depends_on:
      - modbus  # Ensure Modbus starts before Node-RED

# No need for networks section since we're using host networking
