version: '3.8'

services:
  # Modbus Server Container
  modbus-server:
    image: oitc/modbus-server
    container_name: modbus-server
    ports:
      - "5020:5020" # Exposing the Modbus port
    networks:
      - modbus-net
    environment:
      - MODBUS_TCP_PORT=5020
    restart: unless-stopped

  # Node-RED Container
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880" # Exposing the Node-RED web UI port
    networks:
      - modbus-net
    volumes:
      - ./node-red:/data # Mount Node-RED flows to persist them
    restart: unless-stopped

networks:
  modbus-net:
    driver: bridge
