version: '3.8'

services:
  modbus-server:
    build:
      context: .
      dockerfile: Dockerfile.modbus-server
    container_name: linealert-direct-connect_modbus-server
    networks:
      - modbus-net
    ports:
      - "5020:5020"
    restart: always
    environment:
      - MODBUS_LOG_LEVEL=debug
    volumes:
      - ./logs:/var/log/modbus  # Map local directory to container logs
      - ./modbus_config:/app/config  # Optional: To persist configuration files if needed

  node-red:
    build:
      context: .
      dockerfile: Dockerfile.node-red
    container_name: linealert-direct-connect_node-red
    networks:
      - modbus-net
    ports:
      - "1880:1880"
    restart: always
    environment:
      - NODE_RED_LOG_LEVEL=debug
    volumes:
      - ./flows:/data
      - ./logs:/data/logs  # Map local directory to container logs
      - ./node-red_config:/data/.node-red  # Optional: Persist Node-RED settings

networks:
  modbus-net:
    driver: bridge
